### ISSUE TITLE
TLS Error: Auth Username/Password was not provided by peer

### ISSUE THREAD

**Issue by fattalgazi** [iphoting/ovpnmcgen.rb#10]
Hello, thank you for your amazing work.

We are using username/password auth in our server vpn configuration.

How can I spesify username and password in the mobileconfig file?

When I try to connect without username and password , I see this log in the vpn log file:

TLS Error: Auth Username/Password was not provided by peer

Thank you.

**Comment by iphoting** [comment]
Hi,

There isn't specific support for user/pass but you can consider using the `--ovpnconfigfile FILE` option (implemented in d0731f0991b00c2867a1262dd459fb4f4e3f3972) to point to a pre-defined `.ovpn` configuration template.

 Hope this helps!

**Comment by fattalgazi** [comment]
Thanks @iphoting
