### ISSUE TITLE
This is incompatible with the latest version of OpenVPN connect due to breaking changes

### ISSUE THREAD

**Issue by jacobwil** [iphoting/ovpnmcgen.rb#11]
[OpenVPN Connect 1.2.5 came out yesterday](https://twitter.com/OpenVPN/status/950455649443315712) and [no longer supports using certificates that are imported into the system keychain](https://forums.openvpn.net/viewtopic.php?p=75559#p75559). It looks like this is an API restriction from Apple. 

I don't see any solution for including an encrypted private key in a mobile config at this time. I've looked at the sparse OpenVPN Connect documentation and all of the forum posts and the developers haven't offered any concrete guidance. 

I'm not sure how this will get fixed but as of right now the mobile config profiles that this script creates can not work with the version of OpenVPN Connect on the app store.

**Comment by iphoting** [comment]
One forum commenter suggested this workaround: https://forums.openvpn.net/viewtopic.php?f=36&t=25587&start=40#p75668

I have not tried but might be helpful.

**Comment by iphoting** [comment]
Looks I'll implement a new switch `--ne`, to generate profiles with the new `net.openvpn.connect.app.NIP` bundle identifier as it cannot be a new default, resulting in a breaking change.

**Comment by iphoting** [comment]
Prerelease gem published: https://rubygems.org/gems/ovpnmcgen.rb/versions/0.6.0.pre1

Install with `gem install ovpnmcgen.rb --pre`.

Let me know if this potentially resolves/workarounds the v1.2.5 breaking changes.

**Comment by iphoting** [comment]
OpenVPN Connect (iOS) v1.2.6 released.

Based on the release notes, the `--cert` and `--key` workarounds should no longer be required.

**Comment by therealmysteryman** [comment]
I have reverted back to old format of profile and able to connect now. Seem they broke this workaround

**Comment by iphoting** [comment]
Could you all elaborate further on what 1.2.8 broke? So that I can update the Readme file. 

In the 1.2.8 beta, mobileconfig with both key+cert and p12 bundle works with VoD. I have also tested with a pure p12 bundle (without key+cert) and it works nicely with VoD.

**Comment by jacobwil** [comment]
@therealmysteryman do you have the `VPNSubType` of `net.openvpn.connect.app` or the old value? 

@iphoting I haven't had a chance to dig in on this yet—noticed it this morning and will take a closer look after work. 

I wish I could elaborate on what broke. Now when I try to connect to the VPN from iOS Settings the switch just flips back to off and no logs show up in the OpenVPN app.

**Comment by therealmysteryman** [comment]
@jacobwil I have the old value, It seem that removing and reinstalling the same old profile worked for me. Not sure if it a glitch or something with the upgrade that went wrong.

**Comment by jacobwil** [comment]
It does appear that the `VPNSubType` of `net.openvpn.OpenVPN-Connect.vpnplugin` has returned which means that the non `--v12compat` files are not only no longer necessary but don't even work. 

I'm going to close this issue because my old, original mobileconfigs work again and nobody should end up with the incompatible 1.2 versions.

**Comment by ordex** [comment]
> It does appear that the `VPNSubType` of `net.openvpn.OpenVPN-Connect.vpnplugin` has returned

FYI, `net.openvpn.OpenVPN-Connect.vpnplugin` works only because OpenVPN Connect is trying to be backward compatible, but you should switch to the new ID as soon as possible. At some point the old ID will be dropped and not supported anymore.

**Comment by jacobwil** [comment]
Thanks @ordex, I'll update my profiles. I just saw the new(?) [example provisioning profile page](https://docs.openvpn.net/connecting/connecting-to-access-server-with-apple-ios/provisioning-profile-example-1/). 

I'm glad that p12 support is back. Glad you all could get it working again.

**Comment by iphoting** [comment]
In any case, please open an issue to let me know if the tool generates any invalid configs.

Separately, I'm going to update the Readme to add a section on how to access the logs for connections triggered by VoD/Settings.app.

**Comment by iphoting** [comment]
Now that 1.2.9 is released, as well as iOS 11.2.6, something seems to have broken the VoD mechanism that brings connections up… I'm puzzled as the logs don't show anything amiss.
