### ISSUE TITLE
Open VPN Error : Missing External PKI alias

### ISSUE THREAD

**Issue by KYDronePilot** [iphoting/ovpnmcgen.rb#13]
I followed all the instructions and entered the appropriate info for this program, but seem to be getting an immediate error (Shown in the OpenVPN iOS app) every time VoD is triggered and tries to automatically connect: "Open VPN Error : Missing External PKI alias." Any idea what's causing this? If any more info is needed, let me know.

**Comment by iphoting** [comment]
Please see issue #11 and the linked forum threads. Developer will release the next OpenVPN Connect app version to resolve this bug. 

In the meanwhile, you can work around this by using the prerelease gem and supplying the `—cert` and `—key` flags.

**Comment by KYDronePilot** [comment]
Wasn't able to get the prerelease working, but adding the cert and key directly to the xml worked. Thanks!

**Comment by iphoting** [comment]
OpenVPN Connect (iOS) v1.2.6 released.

Based on the release notes, the `--cert` and `--key` workarounds should no longer be required.
