### ISSUE TITLE
SSIDs with Spaces

### ISSUE THREAD

**Issue by trifster** [iphoting/ovpnmcgen.rb#14]
First, thanks for this tool. It works so good!!  I have several trusted-ssids that have spaces in their name. how can i type them within the comma separated values to be included correctly?

Thanks,
trifster

**Comment by iphoting** [comment]
Try specifying the SSIDs like this:
`--trusted-ssid "example,example 2"`

Output snippet:
```
					<dict>
						<key>Action</key>
						<string>Disconnect</string>
						<key>InterfaceTypeMatch</key>
						<string>WiFi</string>
						<key>SSIDMatch</key>
						<array>
							<string>example</string>
							<string>example 2</string>
						</array>
					</dict>
```

**Comment by iphoting** [comment]
No further defect reported/confirmed, closing.
