### ISSUE TITLE
About --p12file file

### ISSUE THREAD

**Issue by tugsjargal1** [iphoting/ovpnmcgen.rb#16]
Dear @iphoting 

I am a newer one for Open VPN. Your tool is very helpful. You are doing great thing. 

--p12file FILE: Path to user PKCS#12 file. (Required)
I have a question. --p12file is required. How do I generate p12file ? 

Thank you.

**Comment by iphoting** [comment]
See https://github.com/iphoting/ovpnmcgen.rb#using-openssl-to-convert-files-into-pkcs12-p12.

**Comment by tugsjargal1** [comment]
You are the great! 
Thank you.

**Comment by tugsjargal1** [comment]
Sorry @iphoting 

How do I generate below 2 files ? 
-inkey path/to/john-ipad.key 
-in path/to/john-ipad.crt

**Comment by iphoting** [comment]
You get the key and cert files from your VPN provider/admin.

**Comment by tugsjargal1** [comment]
In the /etc/openvpn/ folder of the OpenVPN server, 2 .crt files and 2 .key are included: 

ca.crt 
server.crt  
server.key 
ta.key

Are they files you are suggesting ? 

Also I have .ovpn file. This file includes below tags: 
<ca>
<cert>
<key>
<tls-auth>

I was thinking client side .ovpn is important to generate .mobileconfig file. 
I am just little confused :)

Thanks.

**Comment by iphoting** [comment]
Pull out the contents of each tag into its own file and feed it to `ovpnmcgen`.
Example:
```
<key>
xyz
</key>
```
Should go into a key file called `client.key`, with the contents `xyz`. Same for the rest of the tags, i.e., `ca`, `cert`, and `tls-auth`.

**Comment by tugsjargal1** [comment]
Thank you :) You are awesome! I got it.
