### ISSUE TITLE
Synology Diskstation

### ISSUE THREAD

**Issue by PascalMinder** [iphoting/ovpnmcgen.rb#20]
When I export the configuration from the VPN application on my Synology Diskstation, I get ca_bundle.crt and a ca.crt. How can I extract the required pem and key file from it?

**Comment by iphoting** [comment]
Based on my quick reading on <https://www.synology.com/en-global/knowledgebase/DSM/help/VPNCenter/vpn_setup>, cert auth is not supported. Hence, VPN-on-Demand is not supported.
