### ISSUE TITLE
Request to add multiple port/protocol option

### ISSUE THREAD

**Issue by deanpemberton** [iphoting/ovpnmcgen.rb#7]
It would be great if there was an option to allow for specifying multiple ports and protocols to connect to.

eg.

    
    <key>remote.1</key>
      <string>12.34.56.78 1194 udp</string>
    <key>remote.2</key>
      <string>12.34.56.78 443 tcp</string>

**Comment by iphoting** [comment]
I agree with this enhancement. 

How about a flag as such, in additional the default host, already specified with `--host`, etc:
`--remotes "12.34.56.78 1194 tcp","12.34.56.78 443 tcp"`?

What do you think?

**Comment by deanpemberton** [comment]
Looks good to me. I haven't checked if you can specify different hosts (ip
addresses) in the remote section to the one in the host section. Something
to test though :)

On Monday, 5 January 2015, Ronald Ip <notifications@github.com> wrote:

> I agree with this enhancement.
>
> How about a flag as such, in additional the default host, already
> specified with --host, etc:
> --remotes "12.34.56.78 1194 tcp","12.34.56.78 443 tcp"?
>
> What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iphoting/ovpnmcgen.rb/issues/7#issuecomment-68654683>.
>


-- 
Regards,

Dean

**Comment by iphoting** [comment]
Alright, I'll try to implement this over the weekend if time permits. 😀

**Comment by iphoting** [comment]
Implemented in commit 9992011fde5e6c4e298e02a1706b3cb9db39d710. Please test if possible.

**Comment by iphoting** [comment]
Feature released in prerelease version `0.5.0.pre`.

Install with:
`gem install ovpnmcgen.rb --pre`
