### ISSUE TITLE
Establish online configuration

### ISSUE THREAD

**Issue by jau88** [iphoting/ovpnmcgen.rb#9]
Would be great if one could configure a profile using a website to generate opvn profiles (only requiring an iDevice). It could include a setup wizard for inexperienced or new users etc... Thoughts?

**Comment by iphoting** [comment]
I like the idea but I think the logic for a web-view might be better housed in a separate project with this gem powering the output. 

I'll be happy to adapt the gem input/output to fit the needs of a web-application.

**Comment by eskin** [comment]
I think this is not secure. Site author can collect keys and he will have access to vpn servers.

**Comment by iphoting** [comment]
I assume that the one hosting this generator operates the VPN servers also.
